version: "3"
services:
  web:
    image: oskrmarolv/test:devops
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.25"
          memory: 75M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: